version: "2"
services:
  mongodb-service:
   image: localhost:5000/mongo
   ports:
      - "27017:27017"
   networks:
      - mern-app-network
   volumes:
      - mongo-data:/app
  backend:
   image: localhost:5000/backend
   ports:
      - "8000:8000"
   networks:
      - mern-app-network
   depends_on:
      - mongodb-service
  frontend:
   image: localhost:5000/frontend
   stdin_open: true
   ports:
      - "80:80"
   networks:
      - mern-app-network
   depends_on:
      - backend

networks:
   mern-app-network:
      driver: bridge

volumes:
   mongo-data:
      driver: local