apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: exam
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: gh1ta/mini-projet:backendiv10
          ports:
            - containerPort: 8000
              name: nodejs-port
          env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: USER_NAME
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: PASSWORD
          
  selector:
    matchLabels:
      app: backend