apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-statefulset
  namespace: exam
spec:
  serviceName: mongodb-service
  selector:
    matchLabels:
      app: mongodb
  replicas: 2
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb-container
        image: mongo
        imagePullPolicy: "IfNotPresent"
        ports:
        - name: mongodb-port
          containerPort: 27017
          protocol: TCP
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: USER_NAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: PASSWORD
        volumeMounts: 
          - name: mongodb-volume
            mountPath: /var/lib/mongo
      volumes:
      - name: mongodb-volume
        persistentVolumeClaim:
          claimName: server-pv-claim