apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server-pv-claim
  namespace: exam
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi