apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server-pv-claim
  namespace: exam
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi